### ISSUE TITLE
struct offsets may not be correct

### ISSUE THREAD

**Issue by jackland123** [jasonful/lcc#11]
Hi,

It might be me, but element offsets in structs seem to be four times bigger than I would expect e.g. the following extract -
```
typedef struct {
	unsigned	value;
	unsigned	time_high;
	unsigned	time_middle;
	unsigned	time_low;
} SAMPLE;

#define SAMPLES_TO_COLLECT	10
SAMPLE sample_list[SAMPLES_TO_COLLECT];
unsigned sample_idx;

sample_list[sample_idx].value = acc;	
sample_list[sample_idx].time_high   = time_high;
```

Produces -

```
move r2,sample_idx
ld r2,r2,0
lsh r2,r2,2
move r1,sample_list
add r2,r2,r1
move r1,entry.acc
ld r1,r1,0
st r1,r2,0

move r2,sample_idx
ld r2,r2,0
lsh r2,r2,2
//move r1,sample_list+16
move r1,sample_list+4
add r2,r2,r1
move r1,time_high
ld r1,r1,0
st r1,r2,0

```
i.e. an offset of 16 for the second element, when 4 seems to be what's needed.

Incidentally, this is a very useful tool. I didn't bother with the ULP until I found it.

Many thanks

Bob

**Comment by jasonful** [comment]
You're right.  The code would have to do multiplication to calculate the offsets when using arrays of structures, and the ULP cannot do multiplication.  I might be able to get it to work if the size of the struct is a power of 2, because then the code could do a left-shift, but that would be a weird restriction.  I've added a note that arrays of structures are not supported.
